name: Build ART for Host

on: [push]

jobs:
  build-art-host:
    runs-on: ubuntu-22.04
    steps:
    - name: free space
      run: |
        rm -rf ~/.cache
        rm -rf aosp/.repo
        sudo apt clean

    - name: deps
      run: |
        sudo apt update
        sudo apt install -y openjdk-11-jdk git python3 unzip zip curl flex bison g++-multilib \
          gcc-multilib lib32z1-dev libncurses5-dev libxml2-utils zlib1g-dev libc6-dev-i386 \
          libgl1-mesa-dev libx11-dev libreadline-dev libssl-dev bc

    - name: repo tool
      run: |
        curl -o repo https://storage.googleapis.com/git-repo-downloads/repo
        chmod +x repo
        sudo mv repo /usr/local/bin/

    - name: get AOSP
      run: |
        mkdir aosp && cd aosp
        repo init -u https://android.googlesource.com/platform/manifest -b android-14.0.0_r3 --depth=1
        repo sync -c -j4

    - name: build ART
      run: |
        cd aosp
        source build/envsetup.sh
        lunch aosp_x86_64-eng
        m -j$(nproc) art

    - name: upload binaries
      uses: actions/upload-artifact@v4
      with:
        name: art-host-bin
        path: aosp/out/host/linux-x86/bin/
